name: yande_gui
description: "Cross-platform GUI for yande"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.1+26

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.24.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  core:
    path: rust_builder
  flutter_rust_bridge: 2.5.1
  package_info_plus: ^8.1.0
  device_info_plus: ^11.1.0
  permission_handler: ^11.3.1

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  path_provider: ^2.1.4
  visibility_detector: ^0.4.0+2
  path: ^1.9.0
  loading_more_list: ^7.1.0
  extended_image: ^9.0.4
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  flutter_animate: ^4.5.0
  file_picker: ^8.1.3
  i18n: ^4.1.1

  collection: any
dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
flutter:
  uses-material-design: true

  assets:
    - assets/tag_translations/