[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.40"
anyhow = "1.0.82"
lazy_static = "*"

tokio = { version = "1.37.0", features = ["test-util", "full"] }
futures-util = "0.3.30"

[dependencies.reqwest]
version = "0.12.4"
default-features = false
features = ["rustls-tls", "json", "stream"]

[dependencies.serde_json]
version = "1.0.116"

[dependencies.serde]
version = "1.0.116"
features = ["derive"]
