// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Post {
  final int id;
  final String tags;
  final int createdAt;
  final int updatedAt;
  final int creatorId;
  final String author;
  final int change;
  final String source;
  final int score;
  final String md5;
  final int fileSize;
  final String fileExt;
  final String fileUrl;
  final bool isShownInIndex;
  final String previewUrl;
  final int previewWidth;
  final int previewHeight;
  final int actualPreviewWidth;
  final int actualPreviewHeight;
  final String sampleUrl;
  final int sampleWidth;
  final int sampleHeight;
  final int sampleFileSize;
  final String jpegUrl;
  final int jpegWidth;
  final int jpegHeight;
  final int jpegFileSize;
  final String rating;
  final bool isRatingLocked;
  final bool hasChildren;
  final int? parentId;
  final String status;
  final bool isPending;
  final int width;
  final int height;
  final bool isHeld;
  final bool isNoteLocked;

  const Post({
    required this.id,
    required this.tags,
    required this.createdAt,
    required this.updatedAt,
    required this.creatorId,
    required this.author,
    required this.change,
    required this.source,
    required this.score,
    required this.md5,
    required this.fileSize,
    required this.fileExt,
    required this.fileUrl,
    required this.isShownInIndex,
    required this.previewUrl,
    required this.previewWidth,
    required this.previewHeight,
    required this.actualPreviewWidth,
    required this.actualPreviewHeight,
    required this.sampleUrl,
    required this.sampleWidth,
    required this.sampleHeight,
    required this.sampleFileSize,
    required this.jpegUrl,
    required this.jpegWidth,
    required this.jpegHeight,
    required this.jpegFileSize,
    required this.rating,
    required this.isRatingLocked,
    required this.hasChildren,
    this.parentId,
    required this.status,
    required this.isPending,
    required this.width,
    required this.height,
    required this.isHeld,
    required this.isNoteLocked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tags.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      creatorId.hashCode ^
      author.hashCode ^
      change.hashCode ^
      source.hashCode ^
      score.hashCode ^
      md5.hashCode ^
      fileSize.hashCode ^
      fileExt.hashCode ^
      fileUrl.hashCode ^
      isShownInIndex.hashCode ^
      previewUrl.hashCode ^
      previewWidth.hashCode ^
      previewHeight.hashCode ^
      actualPreviewWidth.hashCode ^
      actualPreviewHeight.hashCode ^
      sampleUrl.hashCode ^
      sampleWidth.hashCode ^
      sampleHeight.hashCode ^
      sampleFileSize.hashCode ^
      jpegUrl.hashCode ^
      jpegWidth.hashCode ^
      jpegHeight.hashCode ^
      jpegFileSize.hashCode ^
      rating.hashCode ^
      isRatingLocked.hashCode ^
      hasChildren.hashCode ^
      parentId.hashCode ^
      status.hashCode ^
      isPending.hashCode ^
      width.hashCode ^
      height.hashCode ^
      isHeld.hashCode ^
      isNoteLocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Post &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          creatorId == other.creatorId &&
          author == other.author &&
          change == other.change &&
          source == other.source &&
          score == other.score &&
          md5 == other.md5 &&
          fileSize == other.fileSize &&
          fileExt == other.fileExt &&
          fileUrl == other.fileUrl &&
          isShownInIndex == other.isShownInIndex &&
          previewUrl == other.previewUrl &&
          previewWidth == other.previewWidth &&
          previewHeight == other.previewHeight &&
          actualPreviewWidth == other.actualPreviewWidth &&
          actualPreviewHeight == other.actualPreviewHeight &&
          sampleUrl == other.sampleUrl &&
          sampleWidth == other.sampleWidth &&
          sampleHeight == other.sampleHeight &&
          sampleFileSize == other.sampleFileSize &&
          jpegUrl == other.jpegUrl &&
          jpegWidth == other.jpegWidth &&
          jpegHeight == other.jpegHeight &&
          jpegFileSize == other.jpegFileSize &&
          rating == other.rating &&
          isRatingLocked == other.isRatingLocked &&
          hasChildren == other.hasChildren &&
          parentId == other.parentId &&
          status == other.status &&
          isPending == other.isPending &&
          width == other.width &&
          height == other.height &&
          isHeld == other.isHeld &&
          isNoteLocked == other.isNoteLocked;
}
