// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../yande/model/post.dart';
import '../yande/model/similar.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Post>> getPosts(
        {required List<String> tags,
        required int limit,
        required int page,
        dynamic hint}) =>
    RustLib.instance.api
        .getPosts(tags: tags, limit: limit, page: page, hint: hint);

Future<Similar> getSimilar({required int postId, dynamic hint}) =>
    RustLib.instance.api.getSimilar(postId: postId, hint: hint);

Future<void> downloadToFile(
        {required String url,
        required String filePath,
        required FutureOr<void> Function(int, int) progressCallback,
        dynamic hint}) =>
    RustLib.instance.api.downloadToFile(
        url: url,
        filePath: filePath,
        progressCallback: progressCallback,
        hint: hint);

Future<Uint8List> downloadToMemory(
        {required String url,
        required FutureOr<void> Function(int, int) progressCallback,
        dynamic hint}) =>
    RustLib.instance.api.downloadToMemory(
        url: url, progressCallback: progressCallback, hint: hint);
